.travis.yml
I added Django 1.7.4 that will be tested both on Python 2.7 and 3.x.
I switched the build machine to be docker based since the boot time of the machine in Travis is much much quicker.
I also bumped the rest of the Django versions where needed.
I added travis_retry in order to avoid build failures due to network errors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/lukaszb/django-guardian/296)
=> Updated the build matrix

guardian/admin.py
We can not check for queryset in Django 1.8 as the attribute is no longer available
The getattr function still checks the default parameter and fails with a `AttributeError`
as `super(GuardedModelAdminMixin, self)` has no attribute `getquery`. We also need to
pass a default parameter (`None`) to the second getattr call as this will otherwise fail
as well.
This fixes: #307
=> Use getattr to check is GuardedModelAdminMixin has the attribute queryset

guardian/compat.py, guardian/models.py
Importlib is included in Python 2.7, and will be dropped in Django 1.9 as it is no longer needed
django.contrib.contenttypes.generic will be removed in Django 1.9 and has been replaced by
fields, forms, and admin submodules instead of generic.
This should hopefully fix: #309
Kinda hard to test when all the Django 1.8 stuff ain't working yet. I'll fix it if there is a need to after the Django 1.8 pull-requests are merged :)
=> Use importlib and import GenericForeignKey from from django.contrib.contenttypes.fields

README.rst, example_project/templates/base.html
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

guardian/mixins.py
Hello,
I suggest this changes to consistens support all CRUD operations. It can'be used for django ```CreateView``` without this modification.
Example use case:
```python
class ArticleCreateView(PermissionRequiredMixin, CreateView):
model = Article
permission_object = None
permission_required = ['view_article', 'add_article']
fields = ['title', 'slug', 'content']
```
=> Remove .permission_object in PermissionRequiredMixin

CHANGES, guardian/core.py, guardian/managers.py, guardian/mixins.py, guardian/shortcuts.py, guardian/testapp/tests/test_core.py, guardian/testapp/tests/test_shortcuts.py
Hello,
I updated code from #432 made by @phinjensen to:
- consolidate UserObjectPermissionManager and GroupObjectPermissionManager,
- add efficient implementation of ```assign_perm``` and ```remove_perm``` for bulk action,
- accept ```Permission``` instance as argument for ```assign_perm``` and ```remove_perm```` (Due some working idea on implementations bulk_assign_perm and leave these good changes.).
Greetings,
=> Bulk assign permissions for multiple objects

docs/configuration.rst, guardian/backends.py, guardian/conf/settings.py, guardian/core.py, guardian/ctypes.py, guardian/managers.py, guardian/models.py, guardian/shortcuts.py, guardian/testapp/tests/test_conf.py, guardian/testapp/tests/test_custompkmodel.py, guardian/utils.py
This is an implementation of user settable content type retrieval that I mentioned in  #421. I'd like to hear your thoughts on this strategy. This is just a first version. I still need to complete a few tasks but I wanted to make sure I'm heading in the right direction before I finish this up. Let me know what you think.
Here are the outstanding tasks:
* Add tests
* Add docs
* Remove `get_polymorphic_base_content_type` method as it should be in my project or django-polymorphic.
=> Allow content type retrieval to be overridden.

guardian/shortcuts.py
Make sure get_objects_for_user with default option (use_groups=True and
any_perm=False) benefit from direct foreign keys and do not retrive the
full list in Python.
Also use set() instead of list(), as it's fastest to let Python does
deduplicating rather than database.
I've huge performance benefits with this change. Our application is using django-rest-framwork with [DjangoObjectPermissionsFilter](http://www.django-rest-framework.org/api-guide/filtering/#djangoobjectpermissionsfilter). Our user has access to ~5000 objects though group. Due to the way our group are built, user belong to 2 groups and each group as access to the same ~5000 objects
With a PostgreSQL database (on localhost), I've the following time to show one object:
Test | Average time per get
-------|---------
Using …
=> Improve performance of get_objects_for_user

guardian/utils.py
We use generic FK for your permission and don't yet (shame on us :)) delete permission object when object is deleted.
Therefor we use from time to time clean_orphan_obj_perms... but it iterate over *ALL* permission objects, and we have quiet a lots of them (about 100k)... this cause clean_orphan_obj_perms to cache all objects and consume way to much memory (multiple Gb).
This is a known issue of Django with a known solution: use [iterator](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#iterator).
This PR use iterator() for clean_orphan_obj_perms when iterating over all permission objects.
=> Reduce memory usage of clean_orphan_obj_perms

docs/userguide/assign.rst
In the documentation I found a little error in one of the [example](https://django-guardian.readthedocs.io/en/stable/userguide/assign.html#for-group). It was introduced with #292.
=> Fix group permission example

benchmarks/models.py, docs/userguide/assign.rst, docs/userguide/performance.rst, example_project/articles/models.py
`on_delete` is a [required argument beginning with Django 2.0](https://docs.djangoproject.com/en/1.10/ref/models/fields/#foreignkey) (the current master).  Among others this causes the tests against Django's master to fail.
This PR is not enough to fix the tests against Django's master, but it's a start.
=> Added on_delete to all ForeignKeys

.travis.yml
Django 2.0 requires Python 3.5+
Ref https://docs.djangoproject.com/en/dev/releases/2.0/
=> Exclude Django master + python < 3.5 from test matrix

docs/overview.rst
The links to Django-Athority and Django-Permission were bad. Fixed.
Also corrected some grammatical errors.
=> fixed links

guardian/forms.py, guardian/testapp/tests/test_admin.py
Fixes https://github.com/django-guardian/django-guardian/issues/510. This was caused by queryset not being supported as field values.
Line 589 of forms/widgets.py in django 1.11 was failing.
```
selected = (
force_text(subvalue) in value and
(has_selected is False or self.allow_multiple_selected)
)
```
I added a fix and a failing test previously
=> Fix django admin 1.11 not showing selected permissions

guardian/templatetags/guardian_tags.py, guardian/testapp/tests/test_tags.py
While reading through the documentation I stumbled over `ObjectPermissionChecker.prefetch_perms` which is pretty handy if working in `DetailViews`or  `ListViews` and larger querysets. These modifications work pretty well for me if I instantiate the ObjectPermissionChecker in a view (`ObjectPermissionChecker.prefetch_perms(queryset)`) and then passing the checker instance via the view's context to the template. This saves some queries compared to the current code that doesn't facilitate `prefetch_perms` in https://github.com/django-guardian/django-guardian/blob/devel/guardian/templatetags/guardian_tags.py#L45.
This is just a rough idea with basic testing because I'm not quite sure if I've misunderstood something or if I've overlooked an existing feature or workaround that achieves the …
=> Added a optional checker variable to get_obj_perms

benchmarks/run_benchmarks.py, docs/configuration.rst, docs/userguide/assign.rst
`makemigrations` + `migrate` replaced `syncdb` in Django 1.7, which is no longer supported.
https://docs.djangoproject.com/en/1.7/topics/migrations/
=> Replaced syncdb with makemigrations + migrate

guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
``get_groups_with_perms`` called with ``attach_perms=True`` doesn't filter permissions by content type, so permissions for all objects with the same ``pk`` are returned instead of just permissions for given object.
=> Filter attached perms by ctype in get_groups_with_perms

guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
Fix/Improve the functionality in #246 and #383. Also add tests.
I took code from the PR that @timabbott made and renamed the parameter to `only_with_perms_in` and added a test to check for proper behaviour with the `with_group_users` parameter to `False`.
I want this functionality in the library because I have a few models with multiple permissions so running a `get_users_with_perms` and then manually filtering the result gets old really fast.
@mitar might also be interested.
=> Add kwarg to get_users_with_perms to filter for specific permissions as discussed in #246, #383 (rename, add tests)

guardian/templates/admin/guardian/contrib/grappelli/obj_perms_manage.html
`grp-table` class is now required on HTML <table> with latest Grappelli versions
=> Add missing css class to the Grappelli template

contrib/travis/install.sh
The first commit's intention is to prevent similar issues in the future by failing the test suite if this problem exists.  See https://travis-ci.org/django-guardian/django-guardian/builds/427284349
The second commit fixes the version conflict.
Fixes django-guardian/django-guardian#581
=> Fix silently failing tests

.travis.yml, contrib/travis/install.sh, setup.py, tox.ini
It was a bit tricky to get Travis CI to cooperate.  `services` worked for MySQL, but not for PostgreSQL.  I went with `addons` in the end because it allows one to specify the version.
I'm not sure if tests should run against PostgreSQL 10 and MariaDB 10.3 or against the oldest versions (PostgreSQL [9.4](https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-postgresql-9-3) and MySQL [5.6](https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-mysql-5-5); not sure about MariaDB).
Anyways, it works without adjustments in the code itself. :)
Closes django-guardian/django-guardian#582
=> Add support for Python 3.7

guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
`only_with_perms_in` is only returning the users with a group perm matching the *last* provided permission (rather than all provided permissions in the list).
The only_with_perms_in behaviour was added in pull request #555.
I've also adding a test to prevent regression.
=> Fixing a bug in `only_with_perms_in`

AUTHORS, guardian/exceptions.py, guardian/managers.py, guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py, guardian/testapp/tests/test_utils.py, guardian/utils.py
This allows for using the `assign_perm` shortcut to grant a set of users or groups permissions to an object in bulk.
```
article = Article.objects.get(pk=1)
user_queryset = User.objects.filter(some_attr=some_value).all()
assign_perm("change_article", user_queryset, article)
user_list = [user1, user2, user3, user4]
assign_perm("change_article", user_list, article)
group_queryset = Group.objects.filter(some_attr=some_value).all()
assign_perm("change_article", group_queryset, article)
group_list = [group1, group2, group3, group4]
assign_perm("change_article", group_list, article)
```
=> Allow for adding permission to multiple users or groups

guardian/backends.py, guardian/core.py
Guardian's Backend will no longer crash on permission strings with more than one '.'; instead it will deny permission as django.contrib.auth does.
=> Fix for issue #543

docs/userguide/performance.rst, guardian/__init__.py, guardian/utils.py
This PR adds an optional `enabled` toggle on direct foreign key models that allows you to disable their automatic detection. This is useful so that you can allow the ORM to create the tables and  migrate the data from the generic model tables before using the direct models.
=> Optional direct foreign key model

docs/userguide/admin-integration.rst, docs/userguide/assign.rst
Add a note on how to update to Django 2.1 with existing `view_modelname` permissions.
Closes django-guardian/django-guardian#580
=> [docs] Replace view_modelname permission for Django 2.1+ compat

guardian/backends.py, guardian/core.py
Releasing version 1.5.1 with a fix for Python 2.7 support would be the polite thing to do.  This PR paves the way towards that.
Fixes django-guardian/django-guardian#602
=> Call `string.split` without kwargs for Python 2.7 compat

guardian/backends.py
Have been getting this warning when using the [django test client](https://docs.djangoproject.com/en/2.2/topics/testing/tools/#default-test-client) with guardian setup as an authentication backend. Specifically when calling `client.login(username, password)` with the `client` fixture in `pytest-django`.
Could this break backwards compatibility?
Edit: I see #604 will require a major version bump, so this could easily fit in there.
=> Fix RemovedInDjango21Warning in authenticate signature

guardian/management/__init__.py, guardian/testapp/tests/test_core.py, guardian/testapp/tests/test_management.py
Django provides a keyword argument called `using` to the `post_migrate`
signal handler. This argument tells the handler which database was
migrated.
Previously, the `create_anonymous_user()` function would always try to
use the default database to create the anonymous user. This change uses
the `using` parameter to make sure we use the database that actually
underwent the migration.
Closes: django-guardian/django-guardian#630
=> Use the correct DB in post_migration handler

AUTHORS, guardian/utils.py
Given that the content type comparison is only needed before returning the inner branch, we don't need to resolve the content type immediately as this might result in unnecessary queries (potentially many) when people are using the generic Guardian models anyway
=> Overly optimistic content type queries

docs/configuration.rst, guardian/__init__.py, guardian/conf/settings.py, guardian/core.py, guardian/testapp/tests/test_core.py
I threw this together for our own internal use which involves iterating over many various object types through many libraries and interfaces. It simply wasn't feasible to do explicit prefetching the way that django-guardian currently allows. This expects a pretty vanilla setup so definitely not for everyone, but would be nice to have some out-of-the-box functionality that does this. A query-per-check architecture is too onerous for some people.
=> Auto prefetching for vanilla usecases

guardian/__init__.py, guardian/testapp/tests/test_core.py, guardian/testapp/tests/test_other.py, guardian/utils.py
Original auto prefetch PR lacked tests for cache eviction and refetching. The `evict_obj_perms_cache()` call now also returns False if the cache is not evicted (i.e. doesn't exist), and True if the cache was evicted.
=> Better cache eviction and testing

guardian/managers.py
`FieldDoesNotExist` was moved to `django.core.exceptions` in https://github.com/django/django/commit/8958170755b37ce346ae5257c1000bd936faa3b0 and removed from `django.db.models.fields` in https://github.com/django/django/commit/129583a0d3cf69b08d058cd751d777588801b7ad.
=> Fixed import of FieldDoesNotExist exception.

guardian/templates/admin/guardian/contrib/grappelli/obj_perms_manage.html
`admin_static` was [deprecated](https://docs.djangoproject.com/en/dev/releases/2.1/#features-deprecated-in-2-1) in Django 2.1 and will be [removed](https://docs.djangoproject.com/en/dev/releases/3.0/#features-removed-in-3-0) in 3.0
=> Replace deprecated admin_static with static

guardian/management/__init__.py, guardian/testapp/tests/test_management.py
If the post-migrate signal is fired on a database which doesn't have the user model, skip the logic implemented `get_init_anonymous_user()`. This might be the case when a database router is used to have session somewhere else.
Fixes #650
=> Don't initialise anonymous user on DB where it's not migrated

setup.py
[Python's official documentation](https://packaging.python.org/discussions/install-requires-vs-requirements/) describes that packages should declare their installation dependencies in setup.py in order to play nicely with setuptools.
I enjoy using `django-guardian` in one of my projects, but I currently have to handle it differently than all of my other dependencies because it doesn't use `install_requires`.
I'm not sure whether `bumpversion` needs to be in `install_requires`. Let me know what you think.
Thanks!
=> Add requirements (specifically, Django >= 2.1) to setup.py

guardian/models/__init__.py
BaseObjectPermission and BaseGenericObjectPermission were missing from __init__.py.  This pull just adds these to the import and __all__ 
i.e.
`from guardian.models import BaseObjectPermission, BaseGenericObjectPermission`
should work
rather than having to use `from guardian.models.models ...`
=> Add BaseObjectPermission and BaseGenericObjectPermission to models/__init__ import

contrib/travis/test.sh, guardian/templates/admin/guardian/model/obj_perms_no.html, guardian/templates/admin/guardian/model/obj_perms_yes.html
`staticfiles` was deprecated in 2.1 an has been removed in 3.0
https://docs.djangoproject.com/en/3.0/releases/2.1/#deprecated-features-2-1
=> staticfiles is depreceted since 2.1

guardian/models/models.py
`django.utils.translation.ugettext_lazy()` is deprecated in favor of` django.utils.translation.gettext_lazy()` and will be removed in Django 4.0
=> Remove use of deprecated function.

guardian/models/__init__.py
Defer get obj perms model call until runtime to avoid potential circular dependencies.
For example, in user code using custom generic object permissions do this:
```
from guardian.utils import get_user_obj_perms_model, get_group_obj_perms_model
UserObjectPermission = get_user_obj_perms_model()
GroupObjectPermission = get_group_obj_perms_model()
```
not of this:
```
from guardian.models import UserObjectPermission, GroupObjectPermission
```
1. direct foreign key compatibility already requires the use of `get_user_obj_perms_model()` and `get_user_obj_perms_model()`
2. custom generic object permissions just requires the same use `get_user_obj_perms_model()` and `get_user_obj_perms_model()` as direct foreign key object permissions
=> Fix circular dependency by deferring get obj perms model call

guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
Hi,
Since django 1.8 it is not necessary to use a "set" or a list it can be directly replaced inside the id__in parameter, the queryset will always receive the same type of content type and the validation is not necessary.
=> Improve performance of get_objects_for_user, removing sets

guardian/core.py, guardian/testapp/tests/test_core.py
Bit of an emergency fix here, my fault. Our internal branch was slightly behind and thus we didn't catch until now. The cache isn't actually reused if called from the user object which invokes the django backend. This will cause the cache to return false for all subsequent calls. It wasn't caught by the core tests which skip calls that invoke the django backend entirely, and solely rely on the checker object.
=> Fix cache reuse and add tests that invoke backend

CHANGES
@ad-m Can you create a new release?  2.1.0 is not compatible with Django 3.0 due to django-guardian/django-guardian#649 and django-guardian/django-guardian#661.
I tried to simplify that by getting the release notes started.
=> Release v2.2.0

docs/configuration.rst, docs/overview.rst, docs/userguide/assign.rst
Also update other links to point to latest stable docs rather than insecure versions of Django.
=> Fix broken Django docs link

AUTHORS, guardian/managers.py, guardian/shortcuts.py, guardian/testapp/tests/test_core.py, guardian/testapp/tests/test_shortcuts.py
- Modified the `bulk_assign_perm` function within the`BaseObjectPermissionManager` class to handle a list of objects
- Modified the `assign_perm` shortcut function to handle a list of objects
- Added @DavisRayM to the `AUTHORS` file
Fixes #610
=> Modify 'assign_perm' shortcut to treat lists as a queryset

docs/userguide/check.rst
Right now there is chain of redirection:
http://bitbucket.org/jezdez/django-authority/ -> https://github.com/jezdez/django-authority/ -> https://github.com/jazzband/django-authority
=> Update link to current django-authority repository

contrib/travis/test.sh
Django master changed the `max_length` of `AbstractUser`'s `first_name`.  As a result the tests against django-master are failing.  If we update the migrations, the tests will in combination with all stable releases of django.
=> Run migrations check only if required version of django is installed

guardian/core.py
This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.
=> Use chain.from_iterable in core.py

guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
Fixes django-guardian/django-guardian#606
=> Let shortcut 'remove_perm' work with global permission objects

AUTHORS, docs/userguide/remove.rst
Greetings, I propose to update the "assign" reference to "assign_perm".
To be consistent with the new version of the function and the rest of the docs that directly reference assign_perm.
=> Fix function reference in docs: userguide remove section

guardian/testapp/tests/test_decorators.py
The tests are currently [failing](https://travis-ci.org/github/django-guardian/django-guardian/jobs/728474687) against Django master due to the introduction of the new headers interface. This PR fixes the test. 
The response.headers interface is added in Django 3.2
https://github.com/django/django/commit/dcb69043d0de45bb55998fc418d93c28bc7689ae
=> Fixed headers test for Django 3.2

tox.ini
Travis tests against the django master branch. However, this is missing from the tox matrix.
=> Added djangomaster to tox

guardian/__init__.py
Django 3.2 automatically detects `AppConfig` and therefore this setting is no longer required.  Here is the warning in the CI and the release notes. 
https://docs.djangoproject.com/en/dev/releases/3.2/#automatic-appconfig-discovery
https://travis-ci.org/github/django-guardian/django-guardian/jobs/735548344#L427
=> Fixed default_app_config deprecation

CHANGES, README.rst, docs/develop/testing.rst, docs/index.rst
Missed in django-guardian/django-guardian#736
Supersedes django-guardian/django-guardian#725
=> Mention GitHub Actions instead of Travis CI everywhere

.github/workflows/tests.yml, setup.py, tox.ini
Django 3.2 is currently the only Django release to support Python 3.10: https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django
Django 3.2.9 is needed to fully support Python 3.10 (and fixes `distutils` `DeprecationWarning`). This PR should be ready around November 1 when 3.2.9 is released: https://docs.djangoproject.com/en/4.0/releases/3.2.9/
=> Add support for Python 3.10

.github/workflows/tests.yml, README.rst, setup.py, tox.ini
- Add Django 4.0 support
- Bump MariaDB test image to 10.2 to support Django `main` testing.
When merging, please squash the commits with the GitHub UI.
=> Add Django 4.0 support

guardian/shortcuts.py
In our benchmarks, the current `get_users_with_perms` shortcut is improved by unioning when using the `with_group_users` flag. For our typical usecases, this drops query time by ca. 60% (5ms -> 2ms) with reasonably large production tables running on postgres, and cut the number of queries in half (as we do not force execution of the group id query, which I suspect was done for performance reasons anyway).
Of course, I am sure that other database query planners may perform differently, but it is likely that the union approach still comes out ahead sufficiently by avoiding an outer join on potentially large tables.
=> union users and groups for better perf

.github/workflows/tests.yml, AUTHORS, example_project/settings.py, guardian/shortcuts.py, tox.ini
In order to get guardian back on track and keep it active, we consider it essential that the github actions run properly.
Currently, all tests on the devel branch are failing, as described in https://github.com/django-guardian/django-guardian/issues/818.
With this PR we revert the changes of the last 2 merged PRs, because before these all tests pass, #812 and #768. We should also set up a policy that tests cannot be merged if they fail.
In addition, we introduce minimal changes in this PR that make all checks green again.
We also suggest to investigate #812 and #768 again to see why the problem with the checks occurred. We should re-open the issues.
=> Fix failing checks

docs/develop/overview.rst, docs/develop/testing.rst, docs/userguide/performance.rst, guardian/testapp/tests/test_decorators.py, guardian/testapp/tests/test_orphans.py
There are small typos in:
- docs/develop/overview.rst
- docs/develop/testing.rst
- docs/userguide/performance.rst
- guardian/testapp/tests/test_decorators.py
- guardian/testapp/tests/test_orphans.py
Fixes:
- Should read `requires` rather than `requries`.
- Should read `maintenance` rather than `maintainence`.
- Should read `extremely` rather than `extremaly`.
- Should read `explanation` rather than `explonation`.
- Should read `comparison` rather than `comparaison`.
- Should read `building` rather than `buildin`.
- Should read `assign` rather than `assing`.
- Should read `accordingly` rather than `accordinly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.github/workflows/cd.yml, CHANGES, guardian/__init__.py, setup.cfg, setup.py
This PR updates release workflows, with the aim of getting a release candidate published on PyPI. 
I'll bypass branch protections to merge this piece of work, because to test whether actions are working I need the actions code in the default branch - but typically need to do dozens of little tweaks to get actions right, and this'll never get done if we review each one.
Since no actual code is affected, I hope nobody minds this bypass.
=> Release flow

README.rst
We have a nice helper `guardian.shortcuts.assign_perm`. It abstracts module-level permission (see #766) and direct foreign keys. I personally use it everywhere, so I suggest update example to encourage users to do the same.
=> Use shortcuts.assign_perm in example

.github/workflows/tests.yml, README.rst, setup.py, tox.ini
I'm currently overhauling the build process, tooling and dev tools and the support for python 3.8 is causing a bit of an issue with dev dependencies.
Rather than going back through, pinning versions to earlier ones that supported python 3.8, adding lots of exceptions in the build matrix etc, I'm deprecating support for python 3.8, which is past its EOL date. *This doesn't mean django-guardian won't run on 3.8, it just means that you won't be able to develop it on 3.8, and that it won't be tested on 3.8*.
=> Remove EOL python 3.8

docs/css/readthedocs.css, mkdocs.yml
Small fix to make the sure search text is always readable in dark mode. 
- [readthedocs addon css variable reference](https://docs.readthedocs.com/platform/stable/addons.html\#css-variables-reference)
- [Adding extra css to mkdocs](https://www.mkdocs.org/user-guide/configuration/#extra_css)
This should fix this cosmetic/accessibility issue with the latest version of the docs.
=> Fix readthedocs search text contrast

README.md
The `next` branch has been deleted so the badge URL is wrong.
This follows the latest docs from GitHub for creating a badge
- https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge
=> Fix GitHub Actions badge image

guardian/shortcuts.py, pyproject.toml
1. Adds a fix for `guradian.shortcuts.get_objects_for_user` type annotations, [see discussion in issue 846](https://github.com/django-guardian/django-guardian/issues/864).
2. Adds myself to the list of maintainers. 
closes #864 
Note: I initially also added tox to the `dev` dependency group but reverted that change.
=> Use generic types for get_objects_for_user

guardian/admin.py
Passed obj to `get_group_obj_perms_model` so the function can return a custom permissions model associated to the object, as opposed to the default model. This resolves [this issue](https://github.com/django-guardian/django-guardian/issues/879).
=> passed obj to get_group_obj_perms_model

guardian/apps.py, guardian/shortcuts.py, guardian/testapp/tests/test_shortcuts.py
Like django does in `contenttype` app, this adds a simple and easy method to clear the cache which is used by the shortcuts module and register a signal receiver for `post_migrate` which resets that.
=> Reset content-type cache on post-migrate (refs #865)

guardian/core.py, guardian/testapp/tests/test_core.py
If you run the following code
```python
checker = ObjectPermissionChecker(user)
checker.prefetch_perms([])
```
The error `UnboundLocalError: local variable 'model' referenced before assignment` is thrown.
This PR addresses that issue by defining `model` `ctype` and `pks` at the top of `_get_pks_model_and_ctype`
Closes #519
=> Fixed issue causing prefetch_perms() to throw when passed an empty list

guardian/shortcuts.py
This PR address #933 by fixing the arg typing of `guardian.shortcuts.get_perms_for_model`, which was incorrectly typed as a model object instead of class.
=> [#933] Fix arg typing in get_perms_for_model
