docs/userguide/custom-user-model.rst

typo beteen -->between

---

guardian/admin.py

See https://code.djangoproject.com/wiki/SortedDict
Close #342

Use collections.OrderedDict as SortedDict in admin.py

---

README.rst

- Add extra step to configuration: execute migrations.
- Add imports to usage section so they work when testing from docs.

Update docs: add extra config step and imports on usage

---

guardian/__init__.py
guardian/admin.py
guardian/compat.py
guardian/templates/admin/guardian/model/obj_perms_no.html
guardian/templates/admin/guardian/model/obj_perms_yes.html

This hasn't been tested on django < 1.6, but it definitely works on django 1.8.

Django 1.8 compatibility

---

guardian/shortcuts.py
guardian/testapp/tests/test_shortcuts.py

Allow specifying an empty list of permissions for get_objects_for_user

---

guardian/utils.py

One more fix for issue #370.
For details see https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-from-the-old-api

Use new Model _meta API (Fix #370)

---

guardian/backends.py
guardian/utils.py

Fix error in get_anonymous_user with a custom user model without a username field.

Lookup anonymous user using custom username field

---

guardian/admin.py

Fixed GuardedModelAdminMixin views render for Django 1.10

---

guardian/mixins.py

Hi,
I apologize for mistake made in fa0a49acb17c50fc696904a7b8a5dd2e338fbd80. I unintended revert my commit of #434. I pull requests them again.
Class ```mixins.PermissionListMixin``` probably need docs, but I don't know English enough to write a docs.
Greetings,
---
Hej,
Przepraszam za pomyłkę w fa0a49acb17c50fc696904a7b8a5dd2e338fbd80. Przez przypadek odwrociłem mój commit w #433. Proponuje go ponownie.
Klasa ```mixins.PermissionListMixin``` prawdopodobnie wymaga dokumentacji, ale nie znam angielskiego dostatecznie.
Pozdrawiam,

Add mixins.PermissionListMixin

---

guardian/mixins.py
guardian/testapp/tests/test_mixins.py

Hi,
I apologize for mistake made in fa0a49acb17c50fc696904a7b8a5dd2e338fbd80. I unintended revert my commit of #433. I pull requests them again.
Please review especially comments of prepared tests case. English are not my basic language, so I could write something in a misleading or incorrect grammatically.
Greetings,
---
Hej,
Przepraszam za pomyłkę w fa0a49acb17c50fc696904a7b8a5dd2e338fbd80. Przez przypadek odwrociłem mój commit w #433. Proponuje je ponownie.
Proszę o szczególne przyjrzenie się komentarzom dla przygotowanych przypadków testowych. Język angielski nie jest moim podstawowym, więc mogłem coś napisać w sposób mylący lub niepoprawnie gramatycznie.
Pozdrawiam,

Again remove .permission_object in PermissionRequiredMixin 

---

docs/api/guardian.mixins.rst
guardian/mixins.py
guardian/testapp/models.py
guardian/testapp/tests/templates/list.html
guardian/testapp/tests/test_mixins.py

Hello, 
In #434 I suggested add ```PermissionListMixin```. I expected review and comments before write docs, but pull requests was merged without that. In next django-guardian release I want add ```PermissionListMixin``` with full support, so it's good to add docs and tests.
I expect english and docs syntax review. I don't know English the best and I don't write docs a lot. ```PermissionListMixin.get_required_permissions``` break DRY principle due ```PermissionRequredMixin.get_required_permissions```, but I don't know how to write them to make docs still clear.
I hope for @brianmay  support.
Greetings,

Add docs and update tests for PermissionListMixin

---

guardian/shortcuts.py
guardian/testapp/tests/test_direct_rel.py

Previously this function was recursing for every single group that had permissions on the provided object, causing a large number of queries to be run if many groups had permissions on the object. I have added in an extra test to assert the number of queries run by this function.
I'm not super familiar with this project as I have just started using it, so let me know if there may be anything that I missed. 
Note: the slightly larger than expected diff has been caused by my code re-formatter. I think it is good to have done this, but I can revert those lines that have been re-formatted if you'd prefer.
Thanks!

Reduced number of queries in get_groups_with_perms

---

.travis.yml
CHANGES
README.rst
guardian/utils.py
tox.ini

Fixes django-guardian/django-guardian#497

Added Django 1.11 to test matrix and fixed compatibility

---

docs/develop/overview.rst

@lukaszb , @brianmay , I prepare a instruction how to make a new release. Do you can verify them and check the grammar?

Add release instruction

---

guardian/utils.py

Use render instead of render_to_response for Django >=1.10

---

guardian/forms.py

Now to be changed only rows that has been different from value in database. For example you open the form and just save it, logically that nothing to save, but old code removes not selected rows and adds selected, even if values not changed. My commit fix it.

Optymize method save_obj_perms.

---

.travis.yml
contrib/travis/test.sh
docs/userguide/check.rst
example_project/posts/views.py
guardian/mixins.py
setup.py
tox.ini

This PR also fixes issues with Django 3.0 and Python 3.8.

Add Django 2.2 support

---

AUTHORS
guardian/shortcuts.py
guardian/testapp/tests/test_shortcuts.py

Fixes #640 
Please let me know if there are other areas that need tweaking/testing!

Allow object permissions with dots.

---

guardian/compat.py

Remove url from __all__

---

.travis.yml
contrib/travis/test.sh
guardian/admin.py
guardian/core.py
guardian/forms.py
guardian/testapp/tests/test_admin.py
setup.py
tox.ini

Add support for Django 3.0

---

guardian/shortcuts.py

This code was creating a large number of table joins
"Users that are part of a group that have perms to obj" requires that we join 5 tables: user - m2m - group - m2m - obj
Instead; we perform an intermediate query to fetch all of the groups that have a perm record to the object (a join across 3 tables), and then we fetch all of the users that belong to one of those groups (a join across 3 tables).

Update get_users_with_perms() to avoid a large join

---

docs/develop/overview.rst

Fix simple typo: relase -> release

---

docs/installation.rst

removed "easy_install"

---

CHANGES

I tried the following picking list for the release, so the cherry-pick commands would apply successfully:
```bash
git cherry-pick 9206ee4b32b3c97a7bc60440ce8221d483f1a24a
git cherry-pick 448a6149be8de47a62bd31c71eee1d94e688c5ef
git cherry-pick b12212babd8736015cd5b97a0a45dcc16c58c8a2
git cherry-pick 414d3a4a7bbd0ac4c2ddac85e0dcc098cf130ca1
git cherry-pick b338092f829b631cd59827bf29171f1ab405ff18
git cherry-pick 8e8dab207296ee37aa1d19eaeebfad7d0642f138
git cherry-pick 9c981804bbebe9d91f1d4d78292bedf292745986
git cherry-pick d816cfe4dad04dca78417d9c8613b49822256c60
```

Update CHANGES for v2.3.0

---

.github/workflows/tests.yml
tox.ini

Update tested Django versions to latest patch releases

---

guardian/shortcuts.py

This fixes our use-case regarding https://github.com/django-guardian/django-guardian/issues/189.
In particular the generated query for a benchmark test with 900 possible candidates now only contains the one relevant id (as opposed to all 900) and yields a performance increase of a factor of 100.
Please have a look and tell me what you think!
(I'm also wondering if you would be opposed to some more refactorings as it's obvious that `get_objects_for_user`  and `get_objects_for_group` are very similar and have large stretches of identical code.)

Optimize get_objects_for_* if klass is a queryset

---

AUTHORS
guardian/shortcuts.py

Please see [Git Issue 811](https://github.com/django-guardian/django-guardian/issues/811) for a description of the problem

"Fix" performance enhancement related to #811

---

guardian/testapp/tests/test_other.py

Updating save function of Django to tell it what s updated and not to update the complete model for particular field.

Upating save() function for better performance

---

.github/workflows/cd.yml
CHANGES
guardian/__init__.py
setup.cfg
setup.py

- Add `cd` workflow for publishing package to PyPI and releasing it on GitHub

Add workflow for publishing and releasing package

---

README.md

Most of these look like things missed when the README was converted from RST to Markdown.
- https://github.com/django-guardian/django-guardian/pull/846/commits/864eaf266b34cb8d337c8efd85039c0f1f148ddf
- #846

Fix formatting issues in README

---

pyproject.toml
tox.ini

Support Django 5.2

---

pyproject.toml

Remove unused `mock` install from PyPI

---

.github/workflows/tests.yml
pyproject.toml

CI Commit Check is added. (https://github.com/django-guardian/django-guardian/issues/895)

pre-commit checker step is added

---

README.md

https://djangopackages.org/packages/p/django-guardian/

django-packages badge is added

---

guardian/management/__init__.py
guardian/testapp/tests/test_management.py

https://github.com/django-guardian/django-guardian/issues/770

rollback compatible create anon user fix is developed
